### ISSUE TITLE
The bot not modify the messages and it create a loop of send messages

### ISSUE THREAD

**Issue by MrFiregore** [irazasyed/telegram-bot-sdk#329]
It show me this error and send every time the same message.
```
message : Uncaught Telegram\Bot\Exceptions\TelegramOtherException: Bad Request: message is not modified in /var/www/html/**********/public_html/bot/src/Exceptions/TelegramResponseException.php:58
Stack trace:
#0 /var/www/html/*********/public_html/bot/src/TelegramResponse.php(184): Telegram\Bot\Exceptions\TelegramResponseException::create(Object(Telegram\Bot\TelegramResponse))
#1 /var/www/html/*********z/public_html/bot/src/TelegramResponse.php(214): Telegram\Bot\TelegramResponse->makeException()
#2 /var/www/html/*********z/public_html/bot/src/TelegramResponse.php(65): Telegram\Bot\TelegramResponse->decodeBody()
#3 /var/www/html/********yz/public_html/bot/src/TelegramClient.php(138): Telegram\Bot\TelegramResponse->__construct(Object(Telegram\Bot\TelegramRequest), Object(GuzzleHttp\Psr7\Response))
#4 /var/www/html/****"""""""/public_html/bot/src/TelegramClient.php(119): Telegram\Bot\TelegramClient->getResponse(Object(Telegram\Bot\TelegramRequest), Object(GuzzleHttp\Psr7\Response))
#5 /var/www/html/******** 
 file : /var/www/html/********z/public_html/bot/src/Exceptions/TelegramResponseException.php 
 line : 58 
```

**Comment by irazasyed** [comment]
Please post your code!

We can't debug without checking your code.

**Comment by firegore2** [comment]
First send the photo with this code:

```
$mensaje = $bot->setAsyncRequest(false)->sendPhoto([ 
      'chat_id'=>$message_from['chat_id'],
      'photo'=>"download/".$title.".jpg",
      'caption'=>arrayToMessage($progress)
    ]);
    $mensaje_id=$mensaje->getMessageId();
```


- arrayToMessage : is a function wich return a string depending of the array you send
- $mensaje_id : is the variable that cointains the id of the message sended
Then I make a curl response to check the status of the conversion file (other server take care of it), and it response an json. 
I process the response and update the message sended before with this code:


```
do {
      $ch = curl_init();
      curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
      curl_setopt($ch, CURLOPT_URL,$url_get);
      $result=curl_exec($ch);
      curl_close($ch);
      $response_get=json_decode($result, true);
      if ($response_get['info']['step']!='wait' && $progress['wait']=="Por favor espera...") {
         $progress['wait']="I'm processing the data";
      }
      if ($response_get['info']['step']!='error' && $progress[$response_get['info']['step']]!=$response_get['info']['percent'] && $response_get['info']['step']!="wait") {
        $progress[$response_get['info']['step']]=$response_get['info']['percent'];
        $bot->setAsyncRequest(false)->editMessageCaption([
          'chat_id'=>$message_from['chat_id'],
          'message_id'=>$mensaje_id,
          'caption'=>arrayToMessage($progress)
        ]);
      }
    } while ($response_get['info']['percent']!="100.00" || $response_get['info']['step']!="finished");
```

If the prebius data is the same don't update the caption.The caption should be updating while the server don't finally.

**Comment by mrmrn** [comment]
I have a loop of send message, too.
But in my case, this loop happens when a user block my bot.😐

**Comment by devharandi** [comment]
why loop exception!??!?!?!?!
