### ISSUE TITLE
I am using v2.2.0 of the package and cant run any command 

### ISSUE THREAD

**Issue by marn65** [irazasyed/telegram-bot-sdk#358]
I am using v2.2.0 of this brilliant package and I am wondering how to fire a command by user!!
I used this way for creating a command for my bot:
at first I added bellow line to telegram.php
`        App\Http\Controllers\StartCommand::class
`
then I created StartCommand.php at App\Http\Controllers folder as the documentation example StartCommand.php
then I started webhook and it gaved me
`{"ok":true,"result":true,"description":"Webhook is already set"}`

afterall I used this route for commandhandler and disabled csrf token too:
`Route::post('/test/webhook', function () {
    $update = Telegram::commandsHandler(true);
    return 'salam in revale';
});`
the route can be reached by this [address](https://yamata.herokuapp.com/test/webhook) and its ok.
but in my bot @yamatabot the /start command doesn not work yet.
what step is wrong for me?

**Comment by irazasyed** [comment]
Post your StartCommand code?

**Comment by marn65** [comment]
`<?php

namespace App\Http\Controllers;

use Telegram\Bot\Actions;
use Telegram\Bot\Commands\Command;

class StartCommand extends Command
{
    /**
     * @var string Command Name
     */
    protected $name = "start";

    /**
     * @var string Command Description
     */
    protected $description = "Start Command to get you started";

    /**
     * @inheritdoc
     */
    public function handle($arguments)
    {
        // This will send a message using `sendMessage` method behind the scenes to
        // the user/chat id who triggered this command.
        // `replyWith<Message|Photo|Audio|Video|Voice|Document|Sticker|Location|ChatAction>()` all the available methods are dynamically
        // handled when you replace `send<Method>` with `replyWith` and use the same parameters - except chat_id does NOT need to be included in the array.
        $this->replyWithMessage(['text' => 'Hello! Welcome to our bot, Here are our available commands:']);

        // This will update the chat status to typing...
        $this->replyWithChatAction(['action' => Actions::TYPING]);

        // This will prepare a list of available commands and send the user.
        // First, Get an array of all registered commands
        // They'll be in 'command-name' => 'Command Handler Class' format.
        $commands = $this->getTelegram()->getCommands();

        // Build the list
        $response = '';
        foreach ($commands as $name => $command) {
            $response .= sprintf('/%s - %s' . PHP_EOL, $name, $command->getDescription());
        }

        // Reply with the commands list
        $this->replyWithMessage(['text' => $response]);

        // Trigger another command dynamically from within this command
        // When you want to chain multiple commands within one or process the request further.
        // The method supports second parameter arguments which you can optionally pass, By default
        // it'll pass the same arguments that are received for this command originally.
        $this->triggerCommand('subscribe');
    }
}`

**Comment by irazasyed** [comment]
Looks good to me. Except the `$this->triggerCommand('subscribe');` do you have a subscribe command registered as well? If not, remove that line and try.

**Comment by marn65** [comment]
thank you.
I commented `$this->triggerCommand('subscribe');` but when I /start the bot it does not do any thing! :|
webhook is set and posting to  [this](https://yamata.herokuapp.com/test/webhook) return ok.
but when I use start command to @yamatabot it has no response!

**Comment by irazasyed** [comment]
No problem.

So I need to see some more of your code and the logs.

- Please post your set webhook code.
- Post your `telegram.php` config.
- Post your error log.

**Comment by irazasyed** [comment]
Also, Can you try doing the following:

- Remove webhook
- Setup a GET endpoint with `Telegram::commandsHandler(false);` (Note: **false**).
- Send a command like `/help` from your bot.
- Run the GET endpoint from your browser and make sure to `dd` the response and see if that responded with a list of registered commands?

**Comment by marn65** [comment]
I removed webhook, then send a help command to @yamatabot.
after that I created GET end point as you said and [here](http://yamata.herokuapp.com/commandsHandler) is the output.
in my bot /help works but /start does not work yet

**Comment by irazasyed** [comment]
Ok. Post the above requested code and log file data.

**Comment by marn65** [comment]
I use this form for setting webhook
```

<form action="https://api.telegram.org/botMYTOKEN/setWebhook" method="post" enctype="multipart/form-data">
    Select Certificate to upload:
    <input type="file" name="certificate" id="fileToUpload">
	URL: <input type="text" name="url"  value="https://yamata.herokuapp.com/"><br>
    <input type="submit" value="Upload Certificate" name="submit">
</form>
```
```
I dont know what log do you mean? /storage/logs ?

#14 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#15 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(559): Illuminate\Routing\Route->run()
#16 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(561): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(520): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#35 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(498): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#36 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(174): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#37 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#38 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#53 /home/reka/software/bot/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#54 /home/reka/software/bot/server.php(21): require_once('/home/reka/soft...')
#55 {main}  
[2017-03-19 15:07:31] local.ERROR: ReflectionException: Method App\Http\Controllers\BotController::getCommandsHandler() does not exist in /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php:39
Stack trace:
#0 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php(39): ReflectionMethod->__construct('App\\Http\\Contro...', 'getCommandsHand...')
#1 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php(21): Illuminate\Routing\RouteSignatureParameters::fromClassMethodString('App\\Http\\Contro...')
#2 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Route.php(425): Illuminate\Routing\RouteSignatureParameters::fromAction(Array, 'Illuminate\\Data...')
#3 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/ImplicitRouteBinding.php(20): Illuminate\Routing\Route->signatureParameters('Illuminate\\Data...')
#4 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(633): Illuminate\Routing\ImplicitRouteBinding::resolveForRoute(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Route))
#5 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(39): Illuminate\Routing\Router->substituteImplicitBindings(Object(Illuminate\Routing\Route))
#6 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#7 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(561): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(520): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#23 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Router.php(498): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#24 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(174): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#25 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#26 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#40 /home/reka/software/bot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#41 /home/reka/software/bot/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#42 /home/reka/software/bot/server.php(21): require_once('/home/reka/soft...')
#43 {main}  
```

**Comment by irazasyed** [comment]
Not sure why you'd use a form like that to set your webhook.

You could've just done it directly using the `setWebhook` method.

Also, Your URL seems to be wrong and that's where the problem is.

**Comment by marn65** [comment]
when I use the [link](https://api.telegram.org/bot303161138:AAEJbV3fTqlS2Mjpkoow1UL_JOdkStD2yjc/setWebhook) it gaves `{"ok":true,"result":true,"description":"Webhook was set"}`and then when I want to use [GETUPDATE](https://yamata.herokuapp.com/get-updates) it says `Conflict: can't use getUpdates method while webhook is active`. 
so you mean I must delete webhook and use `setwebhook` method from my application ?

**Comment by irazasyed** [comment]
I meant your webhook URL is wrong as per your code. i.e. `https://yamata.herokuapp.com/` if your route is `/test/webhook` then the full url would be `https://yamata.herokuapp.com/test/webhook`

**Comment by irazasyed** [comment]
In Laravel using my package, you would do something like this:

```php
Telegram::setWebhook(['url' => 'https://yamata.herokuapp.com/test/webhook']);
```

**Comment by marn65** [comment]
WOW!
I created this route:
```
Route::post('/test/webhook', function () {
    Telegram::setWebhook(['url' => 'https://yamata.herokuapp.com/test/webhook']);
    $update = Telegram::commandsHandler(true);
    return 'salam in revale';
});
```
and everything looks broken now. :dagger: even after deleting webhook I have error in [GETUPDATE](https://yamata.herokuapp.com/get-updates)
and nothing work now. all the routes have the same error.

**Comment by irazasyed** [comment]
🤦‍♂️

You're doing it wrong again :| 

`setWebhook` should be on another route and run that only one time to set the webhook.

**Comment by irazasyed** [comment]
Please read the docs properly as well as the Laravel docs.

**Comment by marn65** [comment]
I was wrong with the bot token.
Now I edited the token and webhook is set.
but when I try postman to post to [this route](http://yamata.herokuapp.com/test/webhook) it gave me nothing.
and the commands are not working yet!

**Comment by irazasyed** [comment]
It doesn't work with postman. It's not designed for that. I highly recommend you to go through the docs once again to better understand how this package works. Thanks!

**Comment by marn65** [comment]
thank you for the package and your real time responces.
you are great,man.
