### ISSUE TITLE
Add type checking before performing request

### ISSUE THREAD

**Issue by punyflash** [irazasyed/telegram-bot-sdk#780]
Getting exception when sending the photo:
```php
Telegram::sendPhoto([
    'chat_id' => $this->message->chat->id,
    'photo' => InputFile::create("https://lorempixel.com/320/320/?69826.jpg"),
    'parse_mode' => 'HTML',
    'caption' => $text,
]);
```

Exception log:
```log
[2020-08-28 07:01:34] local.ERROR: Invalid resource type: array {"exception":"[object] (InvalidArgumentException(code: 0): Invalid resource type: array at D:\\xampp\\htdocs\\food-delivery\\vendor\\guzzlehttp\\psr7\\src\\functions.php:116)
[stacktrace]
#0 D:\\xampp\\htdocs\\food-delivery\\vendor\\guzzlehttp\\psr7\\src\\MultipartStream.php(87): GuzzleHttp\\Psr7\\stream_for(Array)
#1 D:\\xampp\\htdocs\\food-delivery\\vendor\\guzzlehttp\\psr7\\src\\MultipartStream.php(70): GuzzleHttp\\Psr7\\MultipartStream->addElement(Object(GuzzleHttp\\Psr7\\AppendStream), Array)
#2 D:\\xampp\\htdocs\\food-delivery\\vendor\\guzzlehttp\\psr7\\src\\MultipartStream.php(31): GuzzleHttp\\Psr7\\MultipartStream->createStream(Array)
#3 D:\\xampp\\htdocs\\food-delivery\\vendor\\guzzlehttp\\guzzle\\src\\Client.php(392): GuzzleHttp\\Psr7\\MultipartStream->__construct(Array)
#4 D:\\xampp\\htdocs\\food-delivery\\vendor\\guzzlehttp\\guzzle\\src\\Client.php(346): GuzzleHttp\\Client->applyOptions(Object(GuzzleHttp\\Psr7\\Request), Array)
#5 D:\\xampp\\htdocs\\food-delivery\\vendor\\guzzlehttp\\guzzle\\src\\Client.php(162): GuzzleHttp\\Client->transfer(Object(GuzzleHttp\\Psr7\\Request), Array)
#6 D:\\xampp\\htdocs\\food-delivery\\vendor\\irazasyed\\telegram-bot-sdk\\src\\HttpClients\\GuzzleHttpClient.php(80): GuzzleHttp\\Client->requestAsync('POST', Object(GuzzleHttp\\Psr7\\Uri), Array)
#7 D:\\xampp\\htdocs\\food-delivery\\vendor\\irazasyed\\telegram-bot-sdk\\src\\TelegramClient.php(75): Telegram\\Bot\\HttpClients\\GuzzleHttpClient->send('https://api.tel...', 'POST', Array, Array, false)
#8 D:\\xampp\\htdocs\\food-delivery\\vendor\\irazasyed\\telegram-bot-sdk\\src\\Traits\\Http.php(305): Telegram\\Bot\\TelegramClient->sendRequest(Object(Telegram\\Bot\\TelegramRequest))
#9 D:\\xampp\\htdocs\\food-delivery\\vendor\\irazasyed\\telegram-bot-sdk\\src\\Traits\\Http.php(198): Telegram\\Bot\\Api->sendRequest('POST', 'sendPhoto', Array)
#10 D:\\xampp\\htdocs\\food-delivery\\vendor\\irazasyed\\telegram-bot-sdk\\src\\Traits\\Http.php(241): Telegram\\Bot\\Api->post('sendPhoto', Array, true)
#11 D:\\xampp\\htdocs\\food-delivery\\vendor\\irazasyed\\telegram-bot-sdk\\src\\Methods\\Message.php(125): Telegram\\Bot\\Api->uploadFile('sendPhoto', Array, 'photo')
#12 [internal function]: Telegram\\Bot\\Api->sendPhoto(Array)
#13 D:\\xampp\\htdocs\\food-delivery\\vendor\\irazasyed\\telegram-bot-sdk\\src\\BotsManager.php(284): call_user_func_array(Array, Array)
#14 D:\\xampp\\htdocs\\food-delivery\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(261): Telegram\\Bot\\BotsManager->__call('sendPhoto', Array)
#15 D:\\xampp\\htdocs\\food-delivery\\app\\Services\\Telegram\\Messages\\DishesCatalog.php(107): Illuminate\\Support\\Facades\\Facade::__callStatic('sendPhoto', Array)
#16 D:\\xampp\\htdocs\\food-delivery\\app\\Console\\Commands\\LongPollingCommand.php(58): App\\Services\\Telegram\\Messages\\DishesCatalog->handle()
#17 [internal function]: App\\Console\\Commands\\LongPollingCommand->handle()
#18 D:\\xampp\\htdocs\\food-delivery\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): call_user_func_array(Array, Array)
#19 D:\\xampp\\htdocs\\food-delivery\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 D:\\xampp\\htdocs\\food-delivery\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#21 D:\\xampp\\htdocs\\food-delivery\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#22 D:\\xampp\\htdocs\\food-delivery\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#23 D:\\xampp\\htdocs\\food-delivery\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(134): Illuminate\\Container\\Container->call(Array)
#24 D:\\xampp\\htdocs\\food-delivery\\vendor\\symfony\\console\\Command\\Command.php(258): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#25 D:\\xampp\\htdocs\\food-delivery\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#26 D:\\xampp\\htdocs\\food-delivery\\vendor\\symfony\\console\\Application.php(911): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 D:\\xampp\\htdocs\\food-delivery\\vendor\\symfony\\console\\Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\LongPollingCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 D:\\xampp\\htdocs\\food-delivery\\vendor\\symfony\\console\\Application.php(140): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 D:\\xampp\\htdocs\\food-delivery\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 D:\\xampp\\htdocs\\food-delivery\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 D:\\xampp\\htdocs\\food-delivery\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 {main}
"} 
```

**Comment by punyflash** [comment]
PHP version 7.4.2
Library version 3.1

**Comment by KielD-01** [comment]
@PunyFlash , I had a try to go with this example I did write:

```php5
class WebHookController extends Controller
{
    public function hook() {
        /** @var Update $update */
        $update = Telegram::commandsHandler(true);

        Telegram::sendPhoto([
            'chat_id' => $update->getChat()->id,
            'photo' => InputFile::create(storage_path('app/public/test_photo.jpeg')),
            'parse_mode' => 'html',
            'caption' => '<b>Test Caption for this Image</b>'
        ]);
    }
}
```

After setting up a webhook and sending a message I have received an answer:

<img width="488" alt="Result : an Image with a bold caption " src="https://user-images.githubusercontent.com/10153164/91605724-977ba980-e979-11ea-8205-3a06e694be0b.png">

Also, I had a try to go with Your example and have got a response to a bot with the next message:
<img width="381" alt="Result : using a Lorem Pixel" src="https://user-images.githubusercontent.com/10153164/91605986-06590280-e97a-11ea-8ba2-2fbd61bf7937.png">

If You are using this inside a command, You don't need to get `chat_id` manually. It would be done automatically.
So, You might need to update or re-install the package, or use the next example:

```php5
$this->sendPhoto([
    'photo' => InputFile::create("https://lorempixel.com/320/320/?69826.jpg"),
    'parse_mode' => 'html',
    'caption' => $text,
]);
```

Hope, this would help You with resolving Your issue.

**Comment by punyflash** [comment]
Oh, I'm feeling dumb now. The issue was that `$text` in my example is an array of strings, which I wanted to implode, but forgot about that. Sorry about bothering.

I think it would be much comfortable to find such errors if there was a type checking before sending a request and exception saying something like: `The given ":key" has the wrong type. Expected ":expected_type", but ":given_type" given`. I'll leave the issue open as a feature request.

**Comment by KielD-01** [comment]
Sure thing, @PunyFlash. I will do You favor and implement this for You.
