### ISSUE TITLE
Bad Request: message text is empty

### ISSUE THREAD

**Issue by xdloc** [irazasyed/telegram-bot-sdk#842]
Application was OK, started to be not OK. Reason unknown, maybe PHP version was updated.
Obviously, text is **not empty**. 

PHP **8.0.2** (cli) (built: Feb  4 2021 14:50:35) ( NTS )
Laravel Lumen: **8.2.3**
Library version: **3.4.1** / dev-develop

```
Bad Request: message text is empty {"exception":"[object] (Telegram\\Bot\\Exceptions\\TelegramResponseException(code: 400): Bad Request: message text is empty at /vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php:67)
[stacktrace]
#0 /vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(101): Telegram\\Bot\\Exceptions\\TelegramResponseException::create()
#1 /vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(82): Telegram\\Bot\\TelegramResponse->makeException()
#2 /vendor/irazasyed/telegram-bot-sdk/src/TelegramResponse.php(52): Telegram\\Bot\\TelegramResponse->decodeBody()
#3 /vendor/irazasyed/telegram-bot-sdk/src/TelegramClient.php(130): Telegram\\Bot\\TelegramResponse->__construct()
#4 /vendor/irazasyed/telegram-bot-sdk/src/TelegramClient.php(82): Telegram\\Bot\\TelegramClient->getResponse()
#5 /vendor/irazasyed/telegram-bot-sdk/src/Traits/Http.php(305): Telegram\\Bot\\TelegramClient->sendRequest()
#6 /vendor/irazasyed/telegram-bot-sdk/src/Traits/Http.php(198): Telegram\\Bot\\Api->sendRequest()
#7 /vendor/irazasyed/telegram-bot-sdk/src/Methods/Message.php(51): Telegram\\Bot\\Api->post()
#8 [internal function]: Telegram\\Bot\\Api->sendMessage()
#9 /vendor/irazasyed/telegram-bot-sdk/src/Answers/Answerable.php(57): call_user_func()
#10 /BotCommands/EventsCommand.php(35): Telegram\\Bot\\Commands\\Command->__call()
#11 [internal function]: App\\BotCommands\\EventsCommand->handle()
#12 /vendor/irazasyed/telegram-bot-sdk/src/Commands/Command.php(185): call_user_func_array()
#13 /vendor/irazasyed/telegram-bot-sdk/src/Commands/CommandBus.php(234): Telegram\\Bot\\Commands\\Command->make()
#14 /vendor/irazasyed/telegram-bot-sdk/src/Commands/CommandBus.php(213): Telegram\\Bot\\Commands\\CommandBus->execute()
#15 /vendor/irazasyed/telegram-bot-sdk/src/Commands/CommandBus.php(177): Telegram\\Bot\\Commands\\CommandBus->process()
#16 /vendor/illuminate/collections/Traits/EnumeratesValues.php(234): Telegram\\Bot\\Commands\\CommandBus->Telegram\\Bot\\Commands\\{closure}()
#17 /vendor/irazasyed/telegram-bot-sdk/src/Commands/CommandBus.php(178): Illuminate\\Support\\Collection->each()
#18 [internal function]: Telegram\\Bot\\Commands\\CommandBus->handler()
#19 /vendor/irazasyed/telegram-bot-sdk/src/Answers/AnswerBus.php(27): call_user_func_array()
#20 /vendor/irazasyed/telegram-bot-sdk/src/Traits/CommandsHandler.php(104): Telegram\\Bot\\Answers\\AnswerBus->__call()
#21 /vendor/irazasyed/telegram-bot-sdk/src/Traits/CommandsHandler.php(53): Telegram\\Bot\\Api->processCommand()
#22 /vendor/irazasyed/telegram-bot-sdk/src/Traits/CommandsHandler.php(42): Telegram\\Bot\\Api->useWebHook()
#23 [internal function]: Telegram\\Bot\\Api->commandsHandler()
#24 /vendor/irazasyed/telegram-bot-sdk/src/BotsManager.php(284): call_user_func_array()
#25 /vendor/illuminate/support/Facades/Facade.php(261): Telegram\\Bot\\BotsManager->__call()
#26 /routes/web.php(29): Illuminate\\Support\\Facades\\Facade::__callStatic()
#27 /vendor/illuminate/container/BoundMethod.php(36): Closure->{closure}()
#28 /vendor/illuminate/container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#29 /vendor/illuminate/container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure()
#30 /vendor/illuminate/container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#31 /vendor/illuminate/container/Container.php(610): Illuminate\\Container\\BoundMethod::call()
#32 /vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(299): Illuminate\\Container\\Container->call()
#33 /vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(264): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute()
#34 /vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(166): Laravel\\Lumen\\Application->handleFoundRoute()
#35 /vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(426): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}()
#36 /vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(172): Laravel\\Lumen\\Application->sendThroughPipeline()
#37 /vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(109): Laravel\\Lumen\\Application->dispatch()
#38 /public/index.php(28): Laravel\\Lumen\\Application->run()
#39 {main}
```

**Comment by hakhagmon** [comment]
how it fix?
